# Markdownlint configuration file
default: true,
line-length: false
no-duplicate-header:
    siblings_only: true
blanks-around-headings: false
heading-increment: false
ul-indent:
    indent: 4
no-inline-html:
  allowed_elements:
    - div
    - script
    - i
    - a
    - img
    - b
    - span
    - p
    - label
    - input
    - button
    - br
    - h5
    - h4
    - h3
    - h2
    - ul
    - li
    - figure
    - sup
    - figcaption
    - iframe
    - table
    - thead
    - tr
    - th
    - tbody
    - td
    - hr
